name:                magic-markup
version:             0.1.0.0
github:              "githubuser/Simre1"
license:             BSD3
author:              "Simon"
copyright:           "2020 Simon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Simre1/magic-markup#readme>

dependencies:
- base >= 4.7 && < 5
- haskell-gi
- haskell-gi-base
- gi-gtk
- text
- unordered-containers

library:
  source-dirs: src

executables:
  magic-markup-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - magic-markup

tests:
  magic-markup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - magic-markup
    - hspec

default-extensions:
  - OverloadedLabels
  - OverloadedStrings
  - GADTs
  - MultiParamTypeClasses
  - TypeFamilies
  - TypeOperators
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - ScopedTypeVariables
  - RankNTypes
  - TypeApplications
  - FunctionalDependencies