name:                reactive-markup
version:             0.1.0.0
github:              "githubuser/Simre1"
license:             MIT
author:              "Simon"
copyright:           "2020 Simon"

extra-source-files:
- README.md

description:         Declarative GUI markup

dependencies:
- base >= 4.7 && < 5
- gi-gtk > 3 && < 4
- text < 1.3
- unordered-containers < 0.3
- containers

library:
  source-dirs: src

executables:
  reactive-markup-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reactive-markup

tests:
  reactive-markup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reactive-markup
    - hspec

default-extensions:
  - OverloadedLabels
  - OverloadedStrings
  - GADTs
  - MultiParamTypeClasses
  - TypeFamilies
  - TypeOperators
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - ScopedTypeVariables
  - RankNTypes
  - TypeApplications
  - FunctionalDependencies