name:                reactive-markup-examples
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/Simre1/reactive-markup#readme
license:             MIT
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web


dependencies:
  - base >= 4.7 && < 5
  - text > 1.2 && < 1.3
  - reactive-markup
  - reactive-markup-gtk
  - colour > 2.3 && < 2.4

executables:
  examples:
    source-dirs:      src
    main:             Main.hs
