name:                reactive-markup-gtk
version:             0.1.0.0
#synopsis:
#description:
github:              "Simre1/reactive-markup"
homepage:            https://github.com/Simre1/reactive-markup#readme
license:             MIT
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here

dependencies:
  - base >= 4.7 && < 5
  - reactive-markup
  - gi-gtk == 3.0.*
  - gi-gdk == 3.0.*
  - haskell-gi-base == 0.23.*
  - text > 1.2 && < 1.3
  - colour > 2.3 && < 2.4
  - transformers == 0.5.6.*

library:
  source-dirs: src

default-extensions:
  - OverloadedLabels
  - OverloadedStrings
  - GADTs
  - MultiParamTypeClasses
  - TypeFamilies
  - TypeOperators
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - ScopedTypeVariables
  - RankNTypes
  - TypeApplications
  - FunctionalDependencies